### ISSUE TITLE
Error Running

### ISSUE THREAD

**Issue by idkjs** [Annmary12/MeetingApp#1]
Thanks for sharing this demo.

I have tried running this project. Following the `README` except the git clone command which I think points to the wrong project, i get the following error in the browser which I can not decipher"

```sh
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/Users/prisc_000/Downloads/MeetingApp/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/index.js:317:13)
    at /Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/prisc_000/Downloads/MeetingApp/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/index.js:317:13)
    at /Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/Users/prisc_000/Downloads/MeetingApp/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/Users/prisc_000/Downloads/MeetingApp/node_modules/express/lib/router/layer.js:95:5)
```

Any guidance would be appreciated. Thank you.

**Comment by Annmary12** [comment]
Hello @idkjs , please can you list out the steps you took to set up.
These are the steps I took to set it up few minutes ago
- clone the repository
- cd into the project
- run: `npm install`
- run: `npm start`
- open another terminal, cd into the project and run: `npm run server`

Note
- Ensure you have `json-server` globally installed: `npm install -g json-server`.
- create `.env` file using the example in `env.example`

Thanks for pointing out the wrong command, I have updated it.

**Comment by idkjs** [comment]
Steps:

1. dotenv: 
```sh

REACT_APP_SECRET=
# REACT_APP_BASE_URL=`http://localhost:${port}`
REACT_APP_BASE_URL=`http://localhost:3001`
```

2. `pnpm install`
3. `npm run server`
4. `npm start`.

## Error Output

```sh
Compiled with warnings.

./src/components/Auth/index.js
  Line 34:23:  Expected '===' and instead saw '=='  eqeqeq

./src/pages/Booking/index.js
  Line 3:8:  'Modal' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/react-dev-utils/10.2.0/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:317:13)
    at /Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/react-dev-utils/10.2.0/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:317:13)
    at /Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/react-dev-utils/10.2.0/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/Users/prisc_000/Downloads/MeetingApp/node_modules/.pnpm/registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
```

Reproduction in this repo: https://github.com/idkjs/MeetingApp
